Upgrade to mongo@4.2.2
HeroCoders/mongodb-adapter pull request #7
Opened 2021-12-29 19:01 UTC by hervinhio

2022-01-03 12:59 UTC, pawelniewie commented
@hervinhio sorry, I'm not going to review it. Added @landaleitan instead, but let @jjaroczynski manage reviewers.

2022-01-10 18:31 UTC, landaleitan requested changes

2022-01-10 18:31 UTC, landaleitan commented on lib/mongodb.js
>  var MongoObjectID = function ObjectID(id) {
We have a function and a variable both named `ObjectId`; can we rename or even delete the variable and use `bson.ObjectId` in the few places where it's needed?

2022-01-10 18:31 UTC, landaleitan commented on lib/mongodb.js
> +        * Module dependencies
The code is repeated here, it looks like an accidental paste.

2022-01-11 18:11 UTC, merged